global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'billing'
    static_configs:
      - targets: ['billing:8002']
  - job_name: 'payments'
    static_configs:
      - targets: ['payments:8004']
